package com.capgemini.dnd.dao;

public class Constants {
	public static final String LOGGER_ERROR_MESSAGE_FAILED_UPDATION = "Updation failed ";
	public static final String UPDATE_EXCEPTION_MESSAGE_FAILURE_DELIVERY = "Updation of delivery status failed ";
	public static final String LOGGER_INFO_MESSAGE_DELIVERY_SUCCESSFUL = "Delivery status updated successfully:";
	public static final String UPDATE_EXCEPTION_MESSAGE_TECHNICAL_PROBLEM = "Tehnical problem occured refer log";
	public static final String UPDATE_EXCEPTION_MESSAGE_DBCONNECTION_ERROR = "Error in closing db connection";
	public static final String LOGGER_INFO_MESSAGE_DELIVERY_FAILED = "Delivery status updated failed";
	public static final String LOGGER_ERROR_FETCH_FAILED = "Fetch failed ";
	public static final String DISPLAY_EXCEPTION_FETCH_FAILED = "Fetching of data failed ";
	public static final String DISPLAY_EXCEPTION_INALID_INPUT = "Invalid Input ";
	public static final String LOGGER_INFO_DISPLAY_SUCCESSFUL = "Displayed successfully:";
	public static final String DISPLAY_EXCEPTION_MESSAGE_TECHNICAL_PROBLEM = "Tehnical problem occured refer log";
	public static final String DISPLAY_EXCEPTION_MESSAGE_DBCONNECTION_ERROR = "Error in closing db connection";
	public static final String DISPLAY_EXCEPTION_NO_RECORDS_FOUND = "No Records Founds";
	public static final String CONNECTION_EXCEPTION_MESSAGE_DBCONNECTION_ERROR = "Database could not be connected!!!";
	public static final String PRODUCT_ID_DOES_NOT_EXISTS_EXCEPTION = "Product Order ID does not exist";
	public static final String RAWMATERIAL_ID_DOES_NOT_EXISTS_EXCEPTION = "RawMaterial Order ID does not exist";
	public static final String DISTRIBUTOR_ID_DOES_NOT_EXISTS_EXCEPTION = "Distributor ID does not exist";
	public static final String SUPPLIER_ID_DOES_NOT_EXISTS_EXCEPTION = "Supplier ID does not exist";
	public static final String PRODUCT_NAME_DOES_NOT_EXISTS_EXCEPTION = "Product name does not exist";
	public static final String RAWMATERIAL_NAME_DOES_NOT_EXISTS_EXCEPTION = "RawMaterial name does not exist";
	public static final String WAREHOUSE_ID_DOES_NOT_EXISTS_EXCEPTION = "Warehouse ID does not exist";
	public static final String LOGGER_ERROR_MESSAGE_QUERY_NOT_EXECUTED = "Could not execute the query";
	public static final String LOGGER_ERROR_MESSAGE_DATABASE_NOT_CONNECTED = "Could not connect to the database";
	public static final String EXIT_DATE_EXCEPTION = "Exit date cannot be before its manufacturing date";
	public static final String ROW_NOT_ADDED_MESSAGE = "Row not added";
	public static final String PARSE_EXCEPTION_INVALID_FORMAT = "InvalidDateFormat";
	public static final String PROCESS_DATE_EXCEPTION_MESSAGE = "Process Date should be after manufacturing date and before expiry date";
	public static final String EMPLOYEE_REGISTRATION_FAILED = "Employee registration failed!!!";
	public static final String ROW_ADDITION_FAILED = "Row addition failed!!! - ";
	public static final String EMPLOYEE_LOGGER_ERROR_DATABASE_NOTCONNECTED = "Database could not be connected!!! - ";
	public static final String EMPLOYEE_LOGGER_ERROR_REGISTRATION_FAILED = "Employee registration failed!!!";
	public static final String EMPLOYEE_LOGGER_ERROR_ROW_ADDTION_FAILED = "Row addition failed!!! - ";
	public static final String EMPLOYEE_LOGGER_ERROR_RECORD_NOT_FOUND = "Employee record not found!!!";
	public static final String EMPLOYEE_LOGGER_ERROR_FETCHING_FAILED = "Fetching of the employee failed!!! - ";
	public static final String EMPLOYEE_LOGGER_NAME_PASSWORD_NOTFOUND = "Employee record with the given username and password not found!!!";
	public static final String EMPLOYEE_LOGGER_ERROR_NOT_A_REGISTRATED_USER = "You are not a registered user!!!";
	public static final String EMPLOYEE_LOGGER_ERROR_NOT_LOGGEDIN = "You are not logged in!!!";
	public static final String EMPLOYEE_LOGGER_ERROR_USER_NOTFOUND = "Username not found!!!";
	public static final String EMPLOYEE_LOGGER_ERROR_NOT_EVERYONE_IS_LOGGED_OUT = "Not everyone is logged out on exiting the application!!!";
	public static final String UPADTED_SUCCESSFULLY_MESSAGE="Updated succesfully";
	public static final String LOGGER_INFO_UPADTED_SUCCESSFULLY_MESSAGE="Displayed successfully:";
	public static final String RMNAME_DOES_NOT_EXISTS_EXCEPTION = "Raw material name doesn't exist";
	public static final String WID_DOES_NOT_EXISTS_EXCEPTION = "Warehouse ID doesn't exist";
	public static final String RAWMATERIAL_ID_DOES_NOT_EXIST_IN_STOCK_EXCEPTION = "Raw material ID doesn't exist in Stock";
	public static final String PRODUCT_ID_DOES_NOT_EXIST_IN_STOCK_EXCEPTION = "Product ID doesn't exist in Stock";
	public static final String PRODUCTNAME_DOES_NOT_EXISTS_EXCEPTION = "Product name doesn't exixt";
	public static final String DATA_INSERTED_MESSAGE = "Data inserted";
	public static final String INCORRECT_PASSWORD_MESSAGE ="Password is incorrect!!!";
	
	public static final String LOGGER_ERROR_MESSAGE_PASSWORD_MISMATCH = "Passwords do not match!!!";
	public static final String LOGGER_ERROR_MESSAGE_PASSWORD_UNCHANGED = "New password matches with old password!!!";
	public static final String LOGGER_ERROR_MESSAGE_PASSWORD_EMPTY = "Password can't be empty or just spaces!!!";
	public static final String LOGGER_ERROR_MESSAGE_WRONG_ANSWER = "Answer to security question is wrong!!!";
	public static final String LOGGER_ERROR_MESSAGE_UNREGISTERED_USER = "You are not a registered user!!!";
}
